""" DISTRIBUCION DE MODULOS
PASOS:
 1. CREAMOS ARCHIVO setup.py EN LA CARPETA RAIZ DEL PROYECTO
 2. CREAMOS UNA CARPETA O PACKAGE DESDE LA RAIZ DEL PROYECTO Y DENTRO DE ESA NUEVA CARPETA UNA SUBCARPETA...
    Y DENTRO DE ESTA SUBCARPETA CREAMOS LOS MODULOS O ARCHIVOS.PY QUE DESEAMOS DISTRIBUIR
 3. CAPTURAMOS LAS LINEAS DE CODIGO DENTRO DE setup.py (ABRIR ESTE ARCHIVO PARA VER LAS LINEAS DE CODIGO)
 4. DESDE LA TERMINAL (CMD) NOS UBICAMOS EN LA CARPETA RAIZ DEL PROYECTO E INGRESAMOS (python setup.py sdist)...
    SE CREARA DOS ARCHIVOS EN LA CARPETA RAIZ DEL PROYECTO LLAMADOS: dist y nombrequeledamosalpaquete.egg-info
 5. DESDE LA TERMINAL (CMD) NOS UBICAMOS EN LA CARPETA QUE SE CREO LLAMADA "dist" E INGRESAMOS...
    (pip install nombredelpaquetesinlaextencion) DAMOS ENTER Y SE EMPEZARA LA INSTALACION
 6. AHORA CONFIRMAMOS QUE ESTE INSTALADA GLOBALMENTE CON EL COMANDO (pip list) Y YA PODEMOS IMPORTAR...
    LOS MODULOS (ESTO SE PUEDE VER EN EL CODIGO DE ABAJO).
"""

# NOTA: LA CARPETA Y SUBCARPETA DE ESTE MODULO YA SE ELIMINARON PORQUE YA ESTA INSTALADO EL PAQUETE ENCAPSULADO...
# DE IGUAL FORMA SE ELIMINO LAS DOS CARPETAS QUE SE CREAN AL ENCAPSULAR EL PAQUETE
from operaciones.basicas.calcular import *  # Importamos el paquete que encapsulamos para distribucion

# FUNCIONES DENTRO DEL MODULO QUE CREAMOS
print(suma(10, 5))
print(resta(10, 5))
print(multiplicacion(10, 5))
print(division(10, 5))
